//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public string Ma_S { get; set; }
        public int So_PN { get; set; }
        public int SoLuongNhap { get; set; }
        public double GiaNhap { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
