//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string Ma_HD { get; set; }
        public string Ma_KH { get; set; }
        public string Ma_S { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string Ma_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual HOADON HOADON1 { get; set; }
        public virtual HOADON HOADON2 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual QUANLINHANVIEN QUANLINHANVIEN { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
