//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLINHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANLINHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string Ma_NV { get; set; }
        public string Ten_NV { get; set; }
        public string SoCMND { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public string ChucVu { get; set; }
        public Nullable<double> Luong { get; set; }
        public Nullable<bool> QuyenTaoPhieuNhap { get; set; }
        public Nullable<bool> QuyenQuanTriNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
